# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-25 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171225_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
