# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-25 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2017, 12, 25, 10, 14, 3, 915758), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2017, 12, 25, 10, 14, 3, 915758)),
        ),
    ]
